version: '{build}'

clone_folder: c:\projects\titansdk

environment:
    matrix:
        - image: Visual Studio 2013
          platform: x64
          configuration: Debug
          JOB: vs2013
          GENERATOR: Visual Studio 12 2013 Win64
        - image: Visual Studio 2015
          platform: x86
          configuration: Release
          JOB: vs2015
          GENERATOR: Visual Studio 14 2015
        - image: Visual Studio 2017
          platform: x64
          configuration: Release
          JOB: vs2017
          GENERATOR: Visual Studio 15 2017 Win64

matrix:
    fast_finish: true

before_build:
    - cmd: mkdir c:\projects\titansdk_build_%JOB%
    - cmd: cd c:\projects\titansdk_build_%JOB%
    - cmd: cmake -G "%GENERATOR%" ..\titansdk
    - cmd: dir c:\projects\titansdk_build_%JOB%

build:
    project: c:\projects\titansdk\titansdk_build_%JOB%\titansdk.sln
    parallel: true
    verbosity: normal
