language: c

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

matrix:
    include:
        - os: linux
          env: JOB=precise GEN="Unix Makefiles"
        - os: linux
          dist: trusty
          env: JOB=trusty GEN="Unix Makefiles"
        - os: osx
          osx_image: xcode7.2
          env: JOB=xcode7 GEN=Xcode
        - os: osx
          osx_image: xcode8.3
          env: JOB=xcode8 GEN=Xcode
        - os: osx
          osx_image: xcode9
          env: JOB=xcode9 GEN=Xcode

install:
    - mkdir titansdk_build_${JOB}
    - cd titansdk_build_${JOB}
    - cmake -G ${GEN} ..

script:
    - make