language: c

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

matrix:
    include:
        - os: linux
          env:
              global:
                  - JOB=precise
                  - GENERATOR='Unix Makefiles'
                  - BUILD_CMD='make generate_header'
        - os: linux
          dist: trusty
          env:
              global:
                  - JOB=trusty
                  - GENERATOR='Unix Makefiles'
                  - BUILD_CMD='make generate_header'
        - os: osx
          osx_image: xcode7.3.1
          env: JOB=xcode7 GENERATOR=Xcode BUILD_CMD="xcodebuild -target generate_header"
          env:
              global:
                  - JOB=xcode7
                  - GENERATOR=Xcode
                  - BUILD_CMD='xcodebuild -target generate_header'
        - os: osx
          osx_image: xcode8.3
          env:
              global:
                  - JOB=xcode8
                  - GENERATOR=Xcode
                  - BUILD_CMD='xcodebuild -target generate_header'
        - os: osx
          osx_image: xcode9
          env:
              global:
                  - JOB=xcode9
                  - GENERATOR=Xcode
                  - BUILD_CMD='xcodebuild -target generate_header'

install:
    - mkdir titansdk_BUILD_CMD_${JOB}
    - cd titansdk_BUILD_CMD_${JOB}
    - cmake -G "${GENERATOR}" ..
    - ${BUILD_CMD}

script:
    - echo todo