language: c

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

matrix:
    include:
        - os: linux
          env:
              global:
                  - JOB=precise
                  - GENERATOR='Unix Makefiles'
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=FALSE'
                  - BUILD_TYPE=Debug
                  - UT=unit_test/unit_test
        - os: linux
          dist: trusty
          env:
              global:
                  - JOB=trusty
                  - GENERATOR='Unix Makefiles'
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=TRUE'
                  - BUILD_TYPE=Release
                  - UT=unit_test/unit_test
        - os: osx
          osx_image: xcode7.3.1
          env: JOB=xcode7 GENERATOR=Xcode BUILD_CMD="xcodebuild -target generate_header"
          env:
              global:
                  - JOB=xcode7
                  - GENERATOR=Xcode
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=FALSE -DPLATFORM_ENABLE_DEBUG=FALSE'
                  - BUILD_TYPE=Debug
                  - UT=unit_test/Debug/unit_test
        - os: osx
          osx_image: xcode8.3
          env:
              global:
                  - JOB=xcode8
                  - GENERATOR=Xcode
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=FALSE -DPLATFORM_ENABLE_DEBUG=TRUE'
                  - BUILD_TYPE=Release
                  - UT=unit_test/Release/unit_test
        - os: osx
          osx_image: xcode9
          env:
              global:
                  - JOB=xcode9
                  - GENERATOR=Xcode
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=FALSE'
                  - BUILD_TYPE=Debug
                  - UT=unit_test/Debug/unit_test

install:
    - mkdir titansdk_BUILD_CMD_${JOB}
    - cd titansdk_BUILD_CMD_${JOB}
    - cmake -G "${GENERATOR}" ${CMAKE_FLAGS} ..
    - cmake --build . --target unit_test --config ${BUILD_TYPE}
    - ${BUILD_CMD}

script:
    - echo start unit test
    - export TT_CASE=case_log_context; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_log_manager; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_sn; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_time; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_logger; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_content; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_func; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_lpatn_line; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_log_pattern; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mutex_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mutex_mt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_atomic_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_atomic_mt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_atomic_cas; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_atomic_ptr; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_atomic_fence; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_spin_lock_basic_mp; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_spin_lock_basic_sp; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_spin_lock_mt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rwlock_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rwlock_mt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_thread_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_thread_sleep; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_thread_rand; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dll; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_process_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fiber_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fiber_3fibers; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fiber_sanity; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fiber_sanity2; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_worker_group; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_task; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fiber_event; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sem_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sem_mt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sem_pc; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sem_count; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_slab_cd; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_slab_allocfree; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mempool_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mempool_alloc_free; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mempool_sanity; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mem_spg; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_mem_page; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_time_abs_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_date_def; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_date_render; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_date_parse; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tmr_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tmr_fiber; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tmr_accuracy; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tmr_stable; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_version; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_high_bit_1; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_low_bit_1; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_base64_dec; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_der_enc; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_strtol; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_c2h; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_align; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_gb2312_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_utf16le_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_utf16be_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_utf32le_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_utf32be_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_charset_utf8; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_clinode; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_u32; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_s32; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_str; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_dir; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_grp_ar; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgnode_bool; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgpath_p2n_abs; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgpath_p2n_rel; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgpath_p2n_dot; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgpath_n2p; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgpath_comp; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_parse_arg; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_ls; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_help; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_pwd; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_cd; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_get; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_set; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_quit; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cfgsh_exec; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fs_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fs_open; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fs_rw; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dir_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fs_multhread; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_fs_consistency; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ipc_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ipc_client; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ipc_stress; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ipc_fiber_ev; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ipc_ev; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sk_addr; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sk_opt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_bind_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tcp_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_udp_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tcp6_close; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tcp4_stress; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_tcp_event; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_udp_event; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_basic_alg_qsort; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_basic_alg_qsort_random; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_basic_alg_bsearch; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_basic_alg_min_larger; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_basic_alg_max_less; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_alg_rng; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptrheap_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptrheap_correct; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptrheap_perf; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_vector; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptr_vector; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_list; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dl_list; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_sl_list; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_hash; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_map_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_map_share_key; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptrmap; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_queue; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptr_queue; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rbtree; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_stack; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ptr_stack; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rbuf; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rbuf_stress; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rbuf_excep; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_wbuf; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rwbuf; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rwbuf_raw; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_null; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_get_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_get_rand; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_put_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_put_rand; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_remove; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buf_get_hexstr; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_buftok; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_blob; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_null; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_getchar; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_cmp; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_copy_swap; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_find; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_join; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_case; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_str_insert; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query_u2t; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query_timeout; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query_exception; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query4_first6; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_query6_first4; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_rr_a; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_rr_aaaa; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_parse_a; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dns_parse_aaaa; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dc_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dc_get_a; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dc_get_aaaa; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dc_exception; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_x509_cert; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_x509_crl; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_basic; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_ver; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_auth; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_alpn; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_resume; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_ticket; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ssl_multhread; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cipher; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_md; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_hmac; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_crypto_ecdh; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_crypto_ecdsa; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rsa_encrypt; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rsa_sign; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_rsa_gen; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_dh; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_entropy; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_ctr_drbg; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xdoc_encoding; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xdoc_parse; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xdoc_render; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xattr_rel; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xattr_bool; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xattr_int; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xnode_bool; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xnode_int; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xnode_rel; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xpath_node; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xpath_attr; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xpath_eval; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_xpath_xpvar; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_line; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_line_stress; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_line_cursor; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_stress; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_ac; ${UT} > /dev/null 2>&1
    - export TT_CASE=case_cli_readline; ${UT} > /dev/null 2>&1
